jdbc:
  createTables: false
  driverClass: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/idde
  username: root
  password: password
  poolSize: 4

spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true

